### ISSUE TITLE
Server/Client crash on shift-punch.

### ISSUE THREAD

**Issue by svinichenko** [SFort/MC-invisframes#9]
Here's the crash report

minecraft version 1.18.2, mod version 2.2.0

---- Minecraft Crash Report ----
// My bad.

Time: 9/2/22, 3:02 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_5974
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.entity.decoration.ItemFrameEntity.handler$cfh000$damage(ItemFrameEntity:551)
	at net.minecraft.entity.decoration.ItemFrameEntity.damage(ItemFrameEntity)
	at net.minecraft.entity.decoration.AbstractDecorationEntity.handleAttack(AbstractDecorationEntity:157)
	at net.minecraft.entity.player.PlayerEntity.attack(PlayerEntity:1183)
	at net.minecraft.server.network.ServerPlayerEntity.attack(ServerPlayerEntity:1438)
	at net.minecraft.server.network.ServerPlayNetworkHandler$1.attack(ServerPlayNetworkHandler:1369)
	at net.minecraft.class_2824$1.handle(class_2824.java:166)
	at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.handle(PlayerInteractEntityC2SPacket:66)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractEntity(ServerPlayNetworkHandler:1339)
	at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.apply(PlayerInteractEntityC2SPacket:53)
	at net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket.apply(PlayerInteractEntityC2SPacket:13)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

**Comment by SFort** [comment]
2.2.0 shouldn't have been tagged for 1.18.2,
thanks have corrected the tags

(please use 2.1.1 for 1.18.2)
